Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/.local/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.local/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/runner/.local/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.local/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.local/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import qat
from qat.core import Schedule

# from qat.qpus import AnalogQPU
from qlmaas.qpus import AnalogQPU

# import qse
from time import time
import qse
import numpy as np
import qat
from qat.core import Schedule

# from qat.qpus import AnalogQPU
from qlmaas.qpus import AnalogQPU

# import qse
from time import time
import pickle
import numpy as np
import pulser
import qutip
from pprint import pprint
from pulser import Pulse, Sequence, Register
import pulser.waveforms
from pulser.waveforms import ConstantWaveform, RampWaveform
from pulser.devices import MockDevice
from pulser_simulation import QutipEmulator, SimConfig
import matplotlib.pyplot as plt
import qse
from pulser.devices import AnalogDevice
------------------


[31m---------------------------------------------------------------------------[39m
[31mModuleNotFoundError[39m                       Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[1][39m[32m, line 2[39m
[32m      1[39m [38;5;28;01mimport[39;00m [34;01mnumpy[39;00m [38;5;28;01mas[39;00m [34;01mnp[39;00m
[32m----> [39m[32m2[39m [38;5;28;01mimport[39;00m [34;01mqat[39;00m
[32m      3[39m [38;5;28;01mfrom[39;00m [34;01mqat[39;00m[34;01m.[39;00m[34;01mcore[39;00m [38;5;28;01mimport[39;00m Schedule
[32m      5[39m [38;5;66;03m# from qat.qpus import AnalogQPU[39;00m

[31mModuleNotFoundError[39m: No module named 'qat'

